//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectricityWeb
{
    public partial class AddBills
    {
        protected global::System.Web.UI.WebControls.TextBox txtCount;
        protected global::System.Web.UI.WebControls.Panel pnlEntry;
        protected global::System.Web.UI.WebControls.TextBox txtConsumerNo;
        protected global::System.Web.UI.WebControls.TextBox txtConsumerName;
        protected global::System.Web.UI.WebControls.TextBox txtUnits;
        protected global::System.Web.UI.WebControls.Label lblEntryMsg;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Button btnFinish;
        protected global::System.Web.UI.WebControls.GridView gvAdded;
        protected global::System.Web.UI.WebControls.Label lblCount;
        protected global::System.Web.UI.WebControls.Label lblDone;
        protected global::System.Web.UI.WebControls.Button btnSetCount;

    }
}
