//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectricityWeb
{
    public partial class RetrieveBills
    {
        protected global::System.Web.UI.WebControls.TextBox txtN;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvBills;
        protected global::System.Web.UI.WebControls.BulletedList bltSummary;

    }
}
